version: '3'

services:
    database:
        image: postgres:15.1
        command: postgres -c 'max_connections=10000'
        volumes:
            - pgdata:/var/lib/postgresql/data/
        environment:
          - POSTGRES_DB=django
          - POSTGRES_USER=django
          - POSTGRES_PASSWORD=django
        logging:
            driver: none


    restapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./restapi:/django
        ports:
            - "8000:8000"
        depends_on:
            - database
        environment:
            DEBUG: "true"
            DATABASE_HOST: "database"

volumes:
    pgdata:
